config/routes.rb
Rails.application.routes.draw do
   namespace :spud do
   	namespace :admin do
         resources :pages do
           get :page_parts, :on => :collection
           get :clear, :on => :collection
           member do
             post 'preview'
           end
         end

         resources :snippets

   		resources :menus do
   			resources :menu_items do
          put :sort, :on => :collection
        end
   		end
   		resources :contacts
   	end
      namespace :cms do
         resource :sitemap,:only => "show"
      end
   end

   if Spud::Cms.config.root_page_name
     root :to => 'pages#show'
   end

   # This is located in lib/spud_cms/page_route.rb to make sure it is loaded last
   # match "*id", :controller => "pages",:action => "show", :as => "page"

end

app/controllers/spud/admin/menu_items_controller.rb
class Spud::Admin::MenuItemsController < Spud::Admin::CmsController
	add_breadcrumb "Menus", :spud_admin_menus_path
	belongs_to_spud_app :menus, :page_title => "Menu Items"
	layout 'spud/admin/detail'
	before_filter :load_menu
	before_filter :load_menu_item, :only => [:edit,:update,:show,:destroy,:reorder]


	def index
		@menu_items = @menu.spud_menu_items.order(:menu_order).includes(:spud_menu_items)
		respond_with @menu_items
	end

	def new
		add_breadcrumb "New", :new_spud_admin_page_path

		@menu_item = @menu.spud_menu_items.new
		respond_with @menu_item
	end

	def create

		add_breadcrumb "New", :new_spud_admin_page_path
		@menu_item = SpudMenuItem.new(menu_item_params)
		@menu_item.spud_menu_id = @menu.id
		if params[:spud_menu_item][:parent_id].blank?
			@menu_item.parent_id = @menu.id
			@menu_item.parent_type = "SpudMenu"
		else
			@menu_item.parent_type = "SpudMenuItem"
		end
		if @menu_item.name.blank? && !@menu_item.spud_page.blank?
			@menu_item.name = @menu_item.spud_page.name
		end
		if @menu_item.menu_order.blank?
			highest_sibling = @menu_item.parent.spud_menu_items.order("menu_order desc").first
			if !highest_sibling.blank?
				@menu_item.menu_order = highest_sibling.menu_order + 1
			end
		end
		flash[:notice] = "Menu Created successfully!" if @menu_item.save



		respond_with @menu_item,:location => spud_admin_menu_menu_items_url
	end

	def edit
		add_breadcrumb "Edit #{@menu_item.name}", :edit_spud_admin_menu_menu_item_path
		if @menu_item.parent_type == "SpudMenu"
			@menu_item.parent_id = nil
		end
		respond_with @menu_item
	end

	def update

		add_breadcrumb "Edit #{@menu_item.name}", :edit_spud_admin_menu_menu_item_path
		if params[:spud_menu_item][:parent_id].blank?
			params[:spud_menu_item][:parent_type] = "SpudMenu"
			params[:spud_menu_item][:parent_id] = @menu.id
		else
			params[:spud_menu_item][:parent_type] = "SpudMenuItem"
		end
		@menu_item.attributes = menu_item_params
		@menu_item.spud_menu_id = @menu.id
		flash[:notice] = "Menu saved successfully!" if @menu_item.save

		respond_with @menu_item,:location => spud_admin_menu_menu_items_url
	end

	def destroy

		flash[:notice] = "Menu Item removed!" if @menu_item.destroy

		respond_with @menu_item,:location => spud_admin_menu_menu_items_url
	end

	def sort
	  menu_orders = ActiveSupport::JSON.decode(params[:menu_order])
	  sort_menu_items_to_parent(@menu, menu_orders)
    render :nothing => true, :status => 200


		#id param
		#source position
		#destination position
		#parent
				# @menu_items = @menu.spud_menu_items.order(:menu_order).includes(:spud_menu_items).paginate :page => params[:page]


	end
private

	def sort_menu_items_to_parent(parent,menu_orders)
		sort_position = 0
		menu_orders.each do |menu_meta|
			menu_item = SpudMenuItem.find(menu_meta["id"])
			if menu_item
				menu_item.menu_order = sort_position
				menu_item.parent = parent
				menu_item.save!
				if menu_meta["order"].nil? == false
					sort_menu_items_to_parent(menu_item, menu_meta["order"])
				end
				sort_position += 1
			end
		end
	end

	def load_menu

		@menu = SpudMenu.where(:id => params[:menu_id]).first

		if @menu.blank?
			flash[:error] = "Menu not found!"
			redirect_to spud_admin_menus_url() and return false
		elsif Spud::Core.multisite_mode_enabled && @menu.site_id != session[:admin_site]
			flash[:warning] = "Site Context Changed. The menu you were viewing is not associated with the current site. Redirected back to menu selections."
			redirect_to spud_admin_menus_url() and return false
		end
		add_breadcrumb "#{@menu.name}", :spud_admin_menu_menu_items_path
	end

	def load_menu_item
		@menu_item = SpudMenuItem.where(:id =>params[:id]).first
		if @menu_item.blank?
			flash[:error] = "Menu Item not found!"
			redirect_to spud_admin_menu_menu_items_url() and return false
		end
	end

	def menu_item_params
		params.require(:spud_menu_item).permit(:name,:parent_type,:parent_id,:item_type,:spud_page_id,:menu_order,:url,:classes)
	end

end

app/views/spud/admin/menu_items/_form.html.erb
<%=error_messages_for(f.object)%>
<fieldset>
<div class="form-group">
	<%=f.label :name, :required=>true,:class => "control-label col-sm-2"%>
	<div class="col-sm-8">
		<%=f.text_field :name,:title => "",:class => "form-control"%>
	</div>

</div>

<div class="form-group">
	<%=f.label :spud_page_id, "Page",:class => "control-label col-sm-2"%>
	<div class="col-sm-8">
	    <%=f.select :spud_page_id,options_for_select(SpudPage.options_tree_for_page(:site_id => session[:admin_site]),@menu_item.spud_page_id),{:include_blank => 'Use URL instead'},{:title => "", :class => "form-control",:onchange => "if($(this).val() != '') {$('#spud_menu_item_url').val('');}"}%>
	</div>

</div>



<div class="form-group">
	<%=f.label :url,:class => "control-label col-sm-2"%>
	<div class="col-sm-8">
		<%=f.text_field :url,:title => "",:class => "form-control"%>
	</div>
</div>
<div class="form-group">
	<%=f.label :classes,:class => "control-label col-sm-2"%>
	<div class="col-sm-8">
		<%=f.text_field :classes,:title => "",:class => "form-control"%>
	</div>
</div>
<div class="form-group">
	<%=f.label :parent, "Parent Menu",:class => "control-label col-sm-2"%>
	<div class="col-sm-8">
		<%=f.select :parent_id,options_for_select(SpudMenuItem.options_tree_for_item(@menu,:filter => @menu_item),@menu_item.parent_type == 'SpudMenuItem' ? @menu_item.parent_id : nil),{:include_blank => "#{@menu.name}"},{:title => "", :class => "form-control"}%>
	</div>

</div>

</fieldset>

app/views/spud/admin/menu_items/_menu_item_row.html.erb
<div class="page_row menu-item-row" data-menu-item-id="<%=menu_item.id%>">

	<span class="row_meta"><%=prefix if defined? prefix%><%=link_to menu_item.name,edit_spud_admin_menu_menu_item_path(:id => menu_item.id)%></span>

	<span class="edit_controls">
		<%=link_to "Edit",edit_spud_admin_menu_menu_item_path(:id => menu_item.id), :title => "Edit Menu Item",:class => 'btn btn-sm btn-link'%>
		&nbsp;&nbsp;
		<%=link_to spud_admin_menu_menu_item_path(:id => menu_item.id),:method => :delete,:class => 'btn btn-sm btn-danger', :data => {:confirm => "Are you sure you want to remove this menu item?"} do%>
			<span class="glyphicon glyphicon-trash"></span>
		<%end%>
	</span>
	<br style="clear:both;"/>
</div>
<ul class="menu_list subitem sortable connectedSortable">

<%if !menu_item.spud_menu_items.all.blank?%>


	<%menu_item.spud_menu_items.order(:menu_order).each do |menu_item|%>
	<li>
		<%=render :partial => 'menu_item_row',:locals => {:menu_item => menu_item}%>
	</li>
	<%end%>



<%end%>
</ul>

app/views/spud/admin/menu_items/edit.html.erb
  

  <%=form_for @menu_item,:url => spud_admin_menu_menu_item_path(:id => @menu_item.id),:html=>{:class=>"form-horizontal"} do |f|%>
    <%=render :partial => "form",:locals => {:f => f}%>
    <div class="form-group">
		<div class="col-sm-8 col-sm-offset-2">
    	<%=f.submit "Save Menu Item", :class=>"btn btn-primary"%> or <%=link_to "cancel",spud_admin_menu_menu_items_path,:class => "btn btn-default"%>
    	</div>
    </div>
  <%end%>

app/views/spud/admin/menu_items/index.html.erb
<%=content_for :data_controls do%>
<%=link_to "New Menu Item",new_spud_admin_menu_menu_item_path(),:class => "btn btn-primary",:title => "New Menu Item"%>
<%end%>
<%=content_for :detail do%>
<p class="lead">Drag and drop to rearrange your menus.</p>
	<ul id="root_menu_list" class="menu_list page_list sortable connectedSortable">
			<%@menu_items.each do |menu_item|%>
        <li>
  				<%=render :partial => "menu_item_row",:locals => {:menu_item => menu_item}%>
        </li>
			<%end%>

	</ul>


<script type="text/javascript">
$(document).ready(function() { spud.admin.cms.menu_items.init(<%=@menu.id%>);})
</script>
<%end%>

app/views/spud/admin/menu_items/new.html.erb
  

  <%=form_for @menu_item,:url => spud_admin_menu_menu_items_path,:html=>{:class=>"form-horizontal"} do |f|%>
    <%=render :partial => "form",:locals => {:f => f}%>
    <div class="form-group">
		<div class="col-sm-8 col-sm-offset-2">
	    	<%=f.submit "Create Menu Item", :class=>"btn btn-primary"%> or <%=link_to "cancel",spud_admin_menu_menu_items_path,:class => "btn btn-default"%>
    	</div>
    </div>
  <%end%>

 