config/routes.rb
Rails.application.routes.draw do
   namespace :spud do
   	namespace :admin do
         resources :pages do
           get :page_parts, :on => :collection
           get :clear, :on => :collection
           member do
             post 'preview'
           end
         end

         resources :snippets

   		resources :menus do
   			resources :menu_items do
          put :sort, :on => :collection
        end
   		end
   		resources :contacts
   	end
      namespace :cms do
         resource :sitemap,:only => "show"
      end
   end

   if Spud::Cms.config.root_page_name
     root :to => 'pages#show'
   end

   # This is located in lib/spud_cms/page_route.rb to make sure it is loaded last
   # match "*id", :controller => "pages",:action => "show", :as => "page"

end

app/views/spud/admin/pages/_form.html.erb
<%=error_messages_for(f.object)%>
<fieldset>
  <legend>Page Title</legend>
  <div class="form-group">
  
    <%=f.label :name, :required=>true,:style =>"display:none;", :class=>"control-label"%>
    <div class="col-sm-12">
      <%=f.text_field :name, :class => "form-control full-width"%>
    </div>
  </div>
</fieldset>
<div id="page_partials_form" class="formtabs tab-content">
  <ul class="formtab_buttons nav nav-tabs">
  </ul>
  <%=f.fields_for :spud_page_partials do |b|%>
    <div class="formtab tab-pane">
      <%=b.hidden_field :name,:class => "tab_name"%>
      <div class="form-group">
        <div class="col-sm-12">
          <%=b.select :format,Spud::Core.renderers.collect { |k,v| [v[:description] || k, k]}, {:include_blank => false}, :class => "pull-right", "data-formatter" => "spud_partial_#{b.object.name.parameterize}"%>
        </div>
      </div>
      <div style="clear:both;">
        <%=b.text_area :content,:class => "spud-formatted-editor", :rows => 10, :id => "spud_partial_#{b.object.name.parameterize}","data-format" => b.object.format%>
      </div>
    </div>
  <%end%>
</div>
<br />
<fieldset>
  <legend>Advanced Settings (optional)</legend>

      <div class="form-group">

        <%=f.label :layout, "Template", :class=>"control-label col-sm-2"%>
        <div class="col-sm-8">
          <%=f.select :layout, options_for_select(layout_options,@page.layout),{},{:title => "", :class => "form-control", 'data-source' => page_parts_spud_admin_pages_path(:page => @page.id) }%>
          <span class="help-inline">Use this to control the layout template to be used for this page if they are available.</span>
        </div>
      </div>

    <div class="form-group">
      <%=f.label :spud_page_id, "Parent Page", :class=>"control-label col-sm-2"%>
      <div class="col-sm-8">
        <%=f.select :spud_page_id,options_for_select(SpudPage.options_tree_for_page(:filter => @page,:site_id => session[:admin_site]),@page.spud_page_id),{:include_blank => 'None'},{:title => "", :class => "form-control"}%>
      </div>
    </div>
    <div class="form-group">

      <%=f.label :url_name, "Perma Link",:disabled => true, :class=>"control-label col-sm-2"%>
      <div class="col-sm-8">
        <%=root_url%><%=f.text_field :url_name,:title => "",:size=>20, :class => "form-control", :disabled => (f.object.use_custom_url_name ? nil : true)%>
        <div class="checkbox">
          <label>
            <%=f.check_box :use_custom_url_name,:onchange => "$('#spud_page_url_name').attr('disabled',!this.checked);"%>
            Customize this pages url    
          </label>
        
        </div>
      </div>
    </div>

</fieldset>
<fieldset>
  <legend>Meta Information (optional)</legend>
  <p>These fields are used to notify search engines about important keywords and the appropriate description to display in a search result.</p>

    <div class="form-group">
      <%=f.label :meta_keywords,"Keywords", :class=>"control-label col-sm-2"%>
      <div class="col-sm-8">
        <%=f.text_field :meta_keywords,:title => "", :class => "form-control"%>
        <span class="help-inline">A Comma seperated list of keywords for search engines. Keep it short (no more than 10 keywords)</span>
      </div>

    </div>
    <div class="form-group">
      <%=f.label :meta_description,"Description", :class => "control-label col-sm-2"%>
      <div class="col-sm-8">
        <%=f.text_area :meta_description,:style => "height:60px;", :class => "form-control"%>
        <span class="help-inline">A short description of the page. This is what appears on a search engines search result page.</span>
      </div>
    </div>
    <div class="form-group">
      <%=f.label :visibility, :class=>"control-label col-sm-2"%>
      <div class="col-sm-8">
        <%=f.select :visibility, [["Public",0],["Private",1]], :class => "form-control"%>
      </div>
    </div>
    <div class="form-group">
      <%=f.label :published, :class=>"control-label col-sm-2"%>
      <div class="col-sm-8">
        <%=f.check_box :published%>
      </div>
    </div>
    <div class="form-group">
      <%=f.label :notes,"Notes", :class=>"control-label col-sm-2"%>
      <div class="col-sm-8">
        <%=f.text_area :notes,:style =>"width:400px;height:40px;"%>
        <span class="help-inline">Have a note to make about this page while you work? Place it here for later.</span>
      </div>
    </div>
  <%=hidden_field_tag "preview",:value => 0%>
</fieldset>

app/views/spud/admin/pages/_page_partials_form.html.erb
<div id="page_partials_form" class="formtabs tab-content">
	<ul class="formtab_buttons nav nav-tabs">
	</ul>
	<% last_index = 0 %>
	<% spud_page_partials.each_with_index do |spud_page_partial, index| %>
		<div class="formtab tab-pane">
			<input type="hidden" class="tab_name" name="spud_page[spud_page_partials_attributes][<%= index %>][name]" value="<%= spud_page_partial.name %>" />
			<textarea class="spud-formatted-editor" name="spud_page[spud_page_partials_attributes][<%= index %>][content]">
				<%= spud_page_partial.content %>
			</textarea>
		</div>
		<% last_index = index + 1 %>
	<% end %>
	<% remove_page_partials.each_with_index do |spud_page_partial, index| %>
		<input type="hidden" name="spud_page[spud_page_partials_attributes][<%= last_index + index %>][id]" value="<%= spud_page_partial.id %>" />
		<input type="hidden" name="spud_page[spud_page_partials_attributes][<%= last_index + index %>][_destroy]", value="1" />
	<% end %>
</div>

app/views/spud/admin/pages/_page_row.html.erb
<div class="page_row">
					
	<span class="row_meta"><%=prefix if defined? prefix%><%=link_to page.name,edit_spud_admin_page_path(:id => page.id)%></span>

	<span class="edit_controls">
		<%=link_to "Preview",spud_admin_page_path(:id => page.id), :title => "Preview",:class => 'btn btn-sm btn-link'%>
		&nbsp;&nbsp;
		<%=link_to spud_admin_page_path(:id => page.id),:method => :delete,:class => 'btn btn-sm btn-danger',:confirm => "Are you sure you want to remove this page?" do%>
			<span class="glyphicon glyphicon-trash"></span>
		<%end%>
	</span>
	<br style="clear:both;"/>
</div>
<%if !page.spud_pages.all.blank?%>
	
		<div class="left_guide">
	
	<%page.spud_pages.each do |spud_page|%>
		<%=render :partial => 'page_row',:locals => {:page => spud_page}%>
	<%end%>
	
		</div>
	
<%end%>

app/views/spud/admin/pages/edit.html.erb
<%=form_for @page,:url => spud_admin_page_path(:id => @page.id),:html=>{:class=>"form-horizontal page_form" } do |f|%>
	<%=render :partial => "form",:locals => {:f => f}%>
    <div class="form-group">
		<div class="col-sm-8 col-sm-offset-2">
	    	<%=f.submit "Save Page", :class=>"btn btn-primary btn-save"%>&nbsp;<%=f.submit "Preview", :class=>"btn btn-info btn-preview"%> or <%=link_to "cancel",spud_admin_pages_path,:class => "btn btn-default"%>
	    </div>
    </div>
<%end%>
<br />
<script type="text/javascript">
$(document).ready(function() {
	$('input[type=submit].btn-preview').click(function(evt) {
		
		$(this).button('reset')
		$('#preview').val(1);
		var form = $('form.page_form')[0];
		form.onsubmit = function() {
			window.open('about:blank','preview_window','width=500,height=400')
		};
		form.target = 'preview_window';
		
	});

	$('input[type=submit].btn-save').click(function(evt) {
		$('#preview').val(0);
		var form = $('form.page_form')[0];
		form.onsubmit = null;
		form.target = null;
	});
	
});

</script>

app/views/spud/admin/pages/index.html.erb
<%=content_for :data_controls do%>
<%=link_to "New Page",spud_core.new_admin_page_path(),:class => "btn btn-primary",:title => "New Page"%>&nbsp;<%=link_to "Clear Cache",spud_core.clear_admin_pages_path(),:class => "btn btn-warning",:title => "Clear Page Cache" if Spud::Cms.cache_mode %>
<%end%>

<%=content_for :detail do%>
	<div class="page_list">
			<%@pages.each do |page|%>
				<%=render :partial => "page_row",:locals => {:page => page}%>
			<%end%>
			<%=will_paginate @pages%>
	</div>

<%end%>

app/views/spud/admin/pages/new.html.erb
<%=form_for @page,:url => spud_admin_pages_path(),:html=>{:class=>"form-horizontal page_form"} do |f|%>
	<%=render :partial => "form",:locals => {:f => f}%>
	<div class="form-group">
		<div class="col-sm-8 col-sm-offset-2">
	    	<%=f.submit "Create Page", :class=>"btn btn-primary form-btn btn-save","data-loading-text"=>"Saving..."%>
	    	&nbsp;
	    	<%=f.submit "Preview", :class=>"btn btn-primary btn-preview"%> or <%=link_to "cancel",spud_admin_pages_path,:class => "btn btn-link"%>
    </div>

<%end%>


  
<script type="text/javascript">
$(document).ready(function() {
	$('input[type=submit].btn-preview').click(function(evt) {
		
		$(this).button('reset')
		$('#preview').val(1);
		var form = $('form.page_form')[0];
		form.onsubmit = function() {
			window.open('about:blank','preview_window','width=500,height=400')
		};
		form.target = 'preview_window';
		
	});

	$('input[type=submit].btn-save').click(function(evt) {
		$('#preview').val(0);
			var form = $('form.page_form')[0];
			form.onsubmit = null;
			form.target = null;
	});
	
});

</script>

app/views/spud/admin/pages/show.html.erb
<%=content_for :head do%>
	<meta name="description" content="<%=@page.meta_description%>" />

	  <meta name="keywords" content="<%=@page.meta_keywords%>" />
<%end%>
<%cache @page do%>
	<%if !@inline.blank?%>
		<%=render :inline => @inline%>
	<%end%>
	<%@page.spud_page_partials.each do |page_partial|%>
		<%cache page_partial do%>
			<%if(page_partial.name.downcase == 'body' && Spud::Cms.yield_body_as_content_block == false)%>
				<%=page_partial.postprocess_content.html_safe%>
			<%else%>
				<%=content_for page_partial.name.parameterize.underscore.to_sym do%>
					<%=page_partial.postprocess_content.html_safe%>
				<%end%>
			<%end%>
		<%end%>
	<%end%>
<%end%>