config/routes.rb
Rails.application.routes.draw do
   namespace :spud do
   	namespace :admin do
         resources :pages do
           get :page_parts, :on => :collection
           get :clear, :on => :collection
           member do
             post 'preview'
           end
         end

         resources :snippets

   		resources :menus do
   			resources :menu_items do
          put :sort, :on => :collection
        end
   		end
   		resources :contacts
   	end
      namespace :cms do
         resource :sitemap,:only => "show"
      end
   end

   if Spud::Cms.config.root_page_name
     root :to => 'pages#show'
   end

   # This is located in lib/spud_cms/page_route.rb to make sure it is loaded last
   # match "*id", :controller => "pages",:action => "show", :as => "page"

end

app/controllers/spud/admin/snippets_controller.rb
class Spud::Admin::SnippetsController < Spud::Admin::ApplicationController
  belongs_to_spud_app :snippets
  layout '/spud/admin/detail'
  add_breadcrumb "Snippets", :spud_admin_snippets_url

  before_filter :load_snippet, :only => [:show, :edit, :update, :destroy]

  # cache_sweeper :snippet_sweeper, :only => [:update,:destroy,:create]

  def index
    @snippets = SpudSnippet.site(session[:admin_site]).order(:name).paginate :page => params[:page]

    respond_with @snippets
  end

  def new
    add_breadcrumb "New", :new_spud_admin_snippet_url
    @snippet = SpudSnippet.new
    respond_with @snippet
  end

  def create
    add_breadcrumb "New", :new_spud_admin_snippet_url
    @snippet = SpudSnippet.new(snippet_params)
    @snippet.site_id = session[:admin_site]

    @snippet.save

    respond_with @snippet, :location => spud_admin_snippets_url
  end

  def edit
    add_breadcrumb "Edit", :edit_spud_admin_snippet_url

    respond_with @snippet
  end

  def update
    add_breadcrumb "Edit", :edit_spud_admin_snippet_url
    flash[:notice] = "Snippet saved successfully!" if @snippet.update_attributes(snippet_params)
    respond_with @snippet, :location => spud_admin_snippets_url
  end

  def destroy
    flash[:notice] = "Snippet removed!" if @snippet.destroy
    respond_with @snippet,:location => spud_admin_snippets_url
  end


private
  def load_snippet
    @snippet = SpudSnippet.where(:id => params[:id]).first
    if @snippet.blank?
      flash[:error] = "Snippet does not exist!"
      redirect_to spud_admin_snippets_url and return false
    elsif Spud::Core.multisite_mode_enabled && @snippet.site_id != session[:admin_site]
      flash[:warning] = "This snippet is for a different site"
      redirect_to spud_admin_snippets_url and return false
    end
  end

  def snippet_params
    params.require(:spud_snippet).permit(:content, :content_processed, :format, :name)
  end
end

app/views/spud/admin/snippets/_form.html.erb
<fieldset>
<div class="form-group">
	<%= f.label :name, :required=>true,:style =>"display:none;", :class => "control-label" %>
	<div class="col-sm-12 ">
		<%= f.text_field :name, :class => "full-width form-control",:placeholder=>"Enter title here" %>
	</div>
</div>
  
  
</fieldset>
<br/>
<div>
  <div class="form-group">
	  <div class="col-sm-12">
	    <%=f.select :format,Spud::Core.renderers.collect { |k,v| [v[:description] || k, k]}, {:include_blank => false}, :class => "pull-right", "data-formatter" => "spud_snippet_content_area"%>
	  </div>
	</div>
	<div style="clear:both;">
	  <%= f.text_area :content,:style => "width:100%;", :id => "spud_snippet_content_area", :class => 'spud-formatted-editor full-width',"data-format" => f.object.format %>
	</div>
</div>

app/views/spud/admin/snippets/edit.html.erb
<%=form_for @snippet,:url => spud_admin_snippet_path(@snippet),:html=>{:class=>"form-horizontal"} do |f|%>
  <%=render :partial => "form",:locals => {:f => f}%>
  <div class="form-group">
		<div class="col-sm-8 col-sm-offset-2">
		    <%=f.submit "Save Snippet", :class=>"btn btn-primary"%> or <%=link_to "cancel",spud_admin_snippets_path,:class => "btn btn-default"%>
	    </div>
  </div>

<%end%>

app/views/spud/admin/snippets/index.html.erb
<%=content_for :data_controls do%>
<%=link_to "New Snippet",new_spud_admin_snippet_path(),:class => "btn btn-primary",:title => "New Snippet"%>
<%end%>
<%=content_for :detail do%>
  <div class="page_list">
      <%@snippets.each do |snippet|%>
        <div class="page_row">

          <span class="row_meta"><%=link_to snippet.name,edit_spud_admin_snippet_path(:id => snippet.id)%></span>

          <span class="edit_controls">

            <%=link_to spud_admin_snippet_path(:id => snippet.id),:method => :delete,:class => 'btn btn-sm btn-danger',:confirm => "Are you sure you want to remove this snippet?" do%>
              <span class="glyphicon glyphicon-trash"></span>
            <%end%>
          </span>
          <br style="clear:both;"/>
        </div>
      <%end%>
      <%=will_paginate @snippets%>

  </div>



<%end%>

app/views/spud/admin/snippets/new.html.erb
<%=form_for @snippet,:url => spud_admin_snippets_path,:html=>{:class=>"form-horizontal"} do |f|%>
  <%=render :partial => "form",:locals => {:f => f}%>
  <div class="form-group">
		<div class="col-sm-8 col-sm-offset-2">
		    <%=f.submit "Create Snippet", :class=>"btn btn-primary"%> or <%=link_to "cancel",spud_admin_snippets_path,:class => "btn btn-default"%>
	    </div>
  </div>

<%end%>