config/routes.rb
Rails.application.routes.draw do
   namespace :spud do
   	namespace :admin do
         resources :pages do
           get :page_parts, :on => :collection
           get :clear, :on => :collection
           member do
             post 'preview'
           end
         end

         resources :snippets

   		resources :menus do
   			resources :menu_items do
          put :sort, :on => :collection
        end
   		end
   		resources :contacts
   	end
      namespace :cms do
         resource :sitemap,:only => "show"
      end
   end

   if Spud::Cms.config.root_page_name
     root :to => 'pages#show'
   end

   # This is located in lib/spud_cms/page_route.rb to make sure it is loaded last
   # match "*id", :controller => "pages",:action => "show", :as => "page"

end

app/controllers/spud/admin/menus_controller.rb
class Spud::Admin::MenusController < Spud::Admin::CmsController
	layout 'spud/admin/detail'
	belongs_to_spud_app :menus
	add_breadcrumb "Menus", :spud_admin_menus_path
	before_filter :load_menu,:only => [:edit,:update,:show,:destroy]

	def index
		@menus = SpudMenu.site(session[:admin_site]).order(:name).paginate :page => params[:page]
		respond_with @menus
	end


	def new
		add_breadcrumb "New", :new_spud_admin_menu_path
		@menu = SpudMenu.new
		respond_with @menu
	end

	def create
		add_breadcrumb "New", :new_spud_admin_menu_path
		@menu = SpudMenu.new(menu_params)
		@menu.site_id = session[:admin_site]
		flash[:notice] = "New menu created" if @menu.save
		respond_with @menu,:location => @menu.id != nil ? spud_admin_menu_menu_items_url(:menu_id => @menu.id) : spud_admin_menus_url
	end

	def edit
		add_breadcrumb "Edit #{@menu.name}", :edit_spud_admin_menu_path
		respond_with @menu
	end

	def update
		add_breadcrumb "Edit #{@menu.name}", :edit_spud_admin_menu_path

		flash[:notice] = "Menu saved successfully" if @menu.update_attributes(menu_params)
		respond_with @menu,:location => spud_admin_menu_menu_items_url(:menu_id => @menu.id)
	end

	def destroy
		flash[:notice] = "Menu removed!" if @menu.destroy
		respond_with @menu,:location => spud_admin_menus_url
	end

private
	def load_menu
		@menu = SpudMenu.where(:id => params[:id]).first
		if @menu.blank?
			flash[:error] = "Menu not found!"
			redirect_to spud_admin_menus_url() and return false
		elsif Spud::Core.multisite_mode_enabled && @menu.site_id != session[:admin_site]
			flash[:warning] = "Site Context Changed. The menu you were viewing is not associated with the current site. Redirected back to menu selections."
			redirect_to spud_admin_menus_url() and return false
		end
	end

	def menu_params
		params.require(:spud_menu).permit(:name, :description)
	end
end

app/views/spud/admin/menus/_form.html.erb
<%=error_messages_for(f.object)%>
<fieldset>
<div class="form-group">
	<%=f.label :name, :required=>true,:class => "control-label col-sm-2"%>
	<div class="col-sm-8">
		<%=f.text_field :name,:title => "",:size=>40, :class => "form-control"%>
	</div>
</div>
</fieldset>

app/views/spud/admin/menus/edit.html.erb
  

  <%=form_for @menu,:url => spud_admin_menu_path(:id => @menu.id),:html=>{:class=>"form-horizontal"} do |f|%>
    <%=render :partial => "form",:locals => {:f => f}%>
    <div class="form-group">
		<div class="col-sm-8 col-sm-offset-2">
	    	<%=f.submit "Save Menu", :class=>"btn btn-primary"%> or <%=link_to "cancel",spud_admin_menus_path,:class => "btn btn-default"%>
    	</div>
    </div>

  <%end%>

app/views/spud/admin/menus/index.html.erb
<%=content_for :data_controls do%>
<%=link_to "New Menu",new_spud_admin_menu_path(),:class => "btn btn-primary",:title => "New Menu"%>
<%end%>
<%=content_for :detail do%>
	<div class="page_list">
			<%@menus.each do |menu|%>
				<div class="page_row">
					
					<span class="row_meta"><%=link_to menu.name,spud_admin_menu_menu_items_path(:menu_id => menu.id)%></span>

					<span class="edit_controls">
						<%=link_to "Edit",edit_spud_admin_menu_path(:id => menu.id),:class => 'btn btn-link btn-sm'%>
						<%=link_to spud_admin_menu_path(:id => menu.id),:method => :delete,:class => 'btn btn-sm btn-danger',:confirm => "Are you sure you want to remove this menu and all items associated with it?" do%>
							<span class="glyphicon glyphicon-trash"></span>
						<%end%>
					</span>
					<br style="clear:both;"/>
				</div>
			<%end%>
			<%=will_paginate @menus%>

	</div>


	
<%end%>

app/views/spud/admin/menus/new.html.erb
<%=form_for @menu,:url => spud_admin_menus_path,:html=>{:class=>"form-horizontal"} do |f|%>
  <%=render :partial => "form",:locals => {:f => f}%>
  <div class="form-group">
		<div class="col-sm-8 col-sm-offset-2">
		    <%=f.submit "Create Menu", :class=>"btn btn-primary"%> or <%=link_to "cancel",spud_admin_menus_path,:class => "btn btn-default"%>
	    </div>
  </div>

<%end%>